#!/bin/bash

jq -r '
  "\(.name) \(.height) \(.weight) \(.types[0].type.name)"
' data.json 2>/dev/null | awk '{
    name = $1
    height = $2 / 10
    weight = $3 / 10
    type = $4
    
    # Capitalize first letter
    name = toupper(substr(name, 1, 1)) substr(name, 2)
    type = toupper(substr(type, 1, 1)) substr(type, 2)
    
    printf "%s is of type %s, weighs %.1fkg, and is %.1fm tall.\n", name, type, weight, height
}'
